#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: manual-evidence.sh [output.md]" >&2
  echo "set SWITCH_CLI_BIN=/path/to/switch-cli to test a packaged binary" >&2
  echo "set SWITCH_CLI_HOME=/abs/path to use an existing switch home" >&2
  echo "without SWITCH_CLI_HOME, a temporary switch home is created and removed" >&2
  echo "refuses to overwrite an existing evidence file" >&2
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

switch_cli="${SWITCH_CLI_BIN:-switch-cli}"
timestamp="$(date -u '+%Y%m%dT%H%M%SZ')"
output="${1:-manual-evidence-${timestamp}.md}"

if [[ -e "${output}" ]]; then
  echo "evidence file already exists: ${output}" >&2
  echo "choose a new output path or remove the existing file first" >&2
  exit 2
fi

if ! command -v "${switch_cli}" >/dev/null 2>&1 && [[ ! -x "${switch_cli}" ]]; then
  echo "switch-cli binary not found: ${switch_cli}" >&2
  usage
  exit 2
fi

umask 077

temporary_switch_home=""
switch_home_note="provided by environment"
if [[ -z "${SWITCH_CLI_HOME:-}" ]]; then
  temporary_switch_home="${HOME:?}/.switch-cli-manual-evidence-${timestamp}-$$"
  mkdir -p "${temporary_switch_home}"
  export SWITCH_CLI_HOME="${temporary_switch_home}"
  switch_home_note="temporary; removed when this script exits"
fi

cleanup() {
  if [[ -n "${temporary_switch_home}" && -d "${temporary_switch_home}" ]]; then
    rm -rf "${temporary_switch_home}"
  fi
}
trap cleanup EXIT

run_section() {
  local title="$1"
  shift
  local tmp
  tmp="$(mktemp)"
  {
    printf '\n## %s\n\n' "${title}"
    printf '```text\n'
    printf '$'
    printf ' %q' "$@"
    printf '\n'
  } >>"${output}"
  if "$@" >"${tmp}" 2>&1; then
    redact_output "${tmp}" >>"${output}"
  else
    local status=$?
    redact_output "${tmp}" >>"${output}"
    printf '\n[exit status: %s]\n' "${status}" >>"${output}"
  fi
  printf '```\n' >>"${output}"
  rm -f "${tmp}"
}

redact_output() {
  sed -E \
    -e 's/[[:alnum:]_.%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}/<email>/g' \
    -e 's/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/<uuid>/g' \
    "$1"
}

{
  printf '# Manual Verification Evidence\n\n'
  printf 'Generated by `scripts/manual-evidence.sh` on `%s`.\n\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf 'This file is a starting point for `docs/manual-verification.md`. Email addresses and UUID-like identifiers are redacted automatically; review it before sharing and redact any additional local paths or identities your release process treats as private.\n\n'
  printf '## Environment\n\n'
  printf -- '- Date: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf -- '- Operator:\n'
  printf -- '- OS and version:\n'
  printf -- '- CPU architecture: %s\n' "$(uname -m)"
  printf -- '- `switch-cli --version`:\n'
  printf -- '- Git commit:\n'
  printf -- '- Claude Code version:\n'
  printf -- '- Codex CLI version:\n'
  printf -- '- `SWITCH_CLI_HOME` used: %s\n' "${SWITCH_CLI_HOME:-<default>}"
  printf -- '- `SWITCH_CLI_HOME` note: %s\n' "${switch_home_note}"
} >"${output}"

run_section "Host OS" uname -a
if command -v sw_vers >/dev/null 2>&1; then
  run_section "macOS Version" sw_vers
elif [[ -r /etc/os-release ]]; then
  run_section "Linux Version" sh -c 'cat /etc/os-release'
fi
run_section "switch-cli Version" "${switch_cli}" --version
if command -v git >/dev/null 2>&1 && git rev-parse --show-toplevel >/dev/null 2>&1; then
  run_section "Git Commit" git rev-parse HEAD
fi
if command -v claude >/dev/null 2>&1; then
  run_section "Claude Code Version" claude --version
else
  {
    printf '\n## Claude Code Version\n\n'
    printf '```text\nclaude not found in PATH\n```\n'
  } >>"${output}"
fi
if command -v codex >/dev/null 2>&1; then
  run_section "Codex CLI Version" codex --version
else
  {
    printf '\n## Codex CLI Version\n\n'
    printf '```text\ncodex not found in PATH\n```\n'
  } >>"${output}"
fi

run_section "switch-cli Doctor" "${switch_cli}" doctor
run_section "Claude Doctor" "${switch_cli}" doctor claude
run_section "Claude Status JSON" "${switch_cli}" status claude --json
run_section "Codex Doctor" "${switch_cli}" doctor codex
run_section "Codex Status JSON" "${switch_cli}" status codex --json

{
  printf '\n## Manual Checklist\n\n'
  printf -- '- [ ] Claude OAuth import on macOS completed if this host is macOS.\n'
  printf -- '- [ ] Claude OAuth import on Linux completed if this host is Linux.\n'
  printf -- '- [ ] Profile switch restart smoke tests completed for available apps.\n'
  printf -- '- [ ] Claude refresh-token rotation behavior recorded.\n'
  printf -- '- [ ] Claude Keychain / oauthAccount mismatch behavior recorded.\n'
  printf -- '- [ ] Claude runtime JSON write/format sampling recorded.\n'
  printf -- '- [ ] Codex external restore flow recorded.\n\n'
  printf 'Detailed steps and passing criteria are in `docs/manual-verification.md`.\n'
} >>"${output}"

echo "wrote ${output}"
