param(
    [Alias("h")]
    [switch]$Help,

    [Parameter(Position = 0)]
    [string]$Output
)

function Show-Usage {
    param([switch]$ErrorStream)

    $lines = @(
        "usage: manual-evidence.ps1 [output.md]",
        "set ANY_SWITCH_BIN=C:\path\to\any-switch.exe to test a packaged binary",
        "set ANY_SWITCH_HOME=C:\Users\you\path-under-home to use an existing any-switch home",
        "without ANY_SWITCH_HOME, a temporary any-switch home is created and removed",
        "refuses to overwrite an existing evidence file"
    )
    foreach ($line in $lines) {
        if ($ErrorStream) {
            [Console]::Error.WriteLine($line)
        } else {
            Write-Output $line
        }
    }
}

if ($Help -or $Output -eq "--help" -or $Output -eq "/?") {
    Show-Usage
    exit 0
}

$ErrorActionPreference = "Stop"
$PSDefaultParameterValues["*:Encoding"] = "utf8"
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
if ([string]::IsNullOrWhiteSpace($Output)) {
    $Output = "manual-evidence-$timestamp.md"
}

if (Test-Path -LiteralPath $Output) {
    Write-Error "evidence file already exists: $Output"
    Write-Error "choose a new output path or remove the existing file first"
    exit 2
}

$anySwitch = $env:ANY_SWITCH_BIN
if ([string]::IsNullOrWhiteSpace($anySwitch)) {
    $packagedBinary = Join-Path (Split-Path -Parent $PSScriptRoot) "any-switch.exe"
    if (Test-Path -LiteralPath $packagedBinary) {
        $anySwitch = $packagedBinary
    } else {
        $anySwitch = "any-switch.exe"
    }
}

$command = Get-Command $anySwitch -ErrorAction SilentlyContinue
if ($null -eq $command -and -not (Test-Path -LiteralPath $anySwitch)) {
    Write-Error "any-switch binary not found: $anySwitch"
    Show-Usage -ErrorStream
    exit 2
}

function Redact-Output {
    param([string]$Text)
    $Text = $Text -replace '[A-Za-z0-9_.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}', '<email>'
    $Text = $Text -replace '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}', '<uuid>'
    $Text = $Text -replace '"(name|displayName|organization_name|organizationName)"\s*:\s*"([^"\\]|\\.)*"', '"$1":"<identity>"'
    $Text = $Text -replace '(^|\s)account=\S+', '$1account=<identity>'
    return $Text
}

function Add-Section {
    param(
        [string]$Title,
        [string]$Command,
        [string[]]$Arguments = @()
    )

    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value "## $Title"
    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value '```text'
    Add-Content -LiteralPath $Output -Value ("$ " + $Command + " " + ($Arguments -join " ")).TrimEnd()

    $status = 0
    try {
        $text = (& $Command @Arguments 2>&1 | Out-String)
        if ($null -ne $global:LASTEXITCODE) {
            $status = $global:LASTEXITCODE
        }
    } catch {
        $text = ($_ | Out-String)
        $status = 1
    }

    Add-Content -LiteralPath $Output -Value (Redact-Output $text).TrimEnd()
    if ($status -ne 0) {
        Add-Content -LiteralPath $Output -Value ""
        Add-Content -LiteralPath $Output -Value "[exit status: $status]"
    }
    Add-Content -LiteralPath $Output -Value '```'
}

$temporarySwitchHome = ""
$switchHomeNote = "provided by environment"
if ([string]::IsNullOrWhiteSpace($env:ANY_SWITCH_HOME)) {
    $homeDir = $env:USERPROFILE
    if ([string]::IsNullOrWhiteSpace($homeDir)) {
        $homeDir = $env:HOME
    }
    if ([string]::IsNullOrWhiteSpace($homeDir)) {
        Write-Error "USERPROFILE or HOME is required when ANY_SWITCH_HOME is not set"
        exit 2
    }
    $temporarySwitchHome = Join-Path $homeDir ".any-switch-manual-evidence-$timestamp-$PID"
    New-Item -ItemType Directory -Path $temporarySwitchHome -Force | Out-Null
    $env:ANY_SWITCH_HOME = $temporarySwitchHome
    $switchHomeNote = "temporary; removed when this script exits"
}

try {
    Set-Content -LiteralPath $Output -Value "# Manual Verification Evidence"
    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value "Generated by ``scripts/manual-evidence.ps1`` on ``$((Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))``."
    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value "This file is a starting point for ``docs/manual-verification.md``. Email addresses, UUID-like identifiers, common JSON identity names, and keychain account labels are redacted automatically; review it before sharing and redact any additional local paths or identities your release process treats as private."
    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value "## Environment"
    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value "- Date: $((Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))"
    Add-Content -LiteralPath $Output -Value "- Operator:"
    Add-Content -LiteralPath $Output -Value "- OS and version:"
    Add-Content -LiteralPath $Output -Value "- CPU architecture: $env:PROCESSOR_ARCHITECTURE"
    Add-Content -LiteralPath $Output -Value "- ``any-switch --version``:"
    Add-Content -LiteralPath $Output -Value "- Git commit:"
    Add-Content -LiteralPath $Output -Value "- Claude Code version:"
    Add-Content -LiteralPath $Output -Value "- Codex CLI version:"
    Add-Content -LiteralPath $Output -Value "- ``ANY_SWITCH_HOME`` used: $env:ANY_SWITCH_HOME"
    Add-Content -LiteralPath $Output -Value "- ``ANY_SWITCH_HOME`` note: $switchHomeNote"

    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value "## PowerShell Version"
    Add-Content -LiteralPath $Output -Value ""
    Add-Content -LiteralPath $Output -Value '```text'
    Add-Content -LiteralPath $Output -Value ($PSVersionTable | Out-String).TrimEnd()
    Add-Content -LiteralPath $Output -Value '```'

    Add-Section "any-switch Version" $anySwitch @("--version")
    Add-Section "any-switch Apps" $anySwitch @("apps")
    Add-Section "any-switch Doctor" $anySwitch @("doctor")
    Add-Section "Claude Doctor" $anySwitch @("doctor", "claude")
    Add-Section "Claude Status JSON" $anySwitch @("status", "claude", "--json")
    Add-Section "Codex Doctor" $anySwitch @("doctor", "codex")
    Add-Section "Codex Status JSON" $anySwitch @("status", "codex", "--json")

    $manualSections = @'

## Local Gate

- [ ] `scripts/verify-local.sh` passed.

Evidence:

```text
paste command summary here
```

## Evidence Summary

Use `pending`, `passed`, `failed`, or `skipped: <linked issue>` as the status.
For the current release stage, the macOS Claude OAuth import evidence is
release-blocking. Broader restart, risk-experiment, Linux, and Windows evidence
is deferred and must have follow-up tracking before this stage is released. Use
``docs/evidence-followups.md`` for in-repository tracking until a repository issue
or release checklist exists. Do not claim full section 13 coverage while any
deferred item is still pending, failed, or skipped.

### Current-Stage Release Blockers

| Item | Status | Evidence location or follow-up issue |
|------|--------|---------------------------------------|
| 2: macOS Claude OAuth import | pending | |

### Deferred Follow-Up Evidence

| Item | Status | Evidence location or follow-up issue |
|------|--------|---------------------------------------|
| 5-macOS: restart smoke tests | pending | ``docs/evidence-followups.md`` |
| A-macOS: Claude refresh-token rotation | pending | ``docs/evidence-followups.md`` |
| B-macOS: Claude source mismatch behavior | pending | ``docs/evidence-followups.md`` |
| C-macOS: Claude runtime JSON sampling | pending | ``docs/evidence-followups.md`` |
| E-macOS: Codex external restore flow | pending | ``docs/evidence-followups.md`` |
| 3: Linux Claude OAuth import | pending | ``docs/evidence-followups.md`` |
| 5-Linux: restart smoke tests | pending | ``docs/evidence-followups.md`` |
| 5-Windows: restart smoke tests | pending | ``docs/evidence-followups.md`` |
| W: Windows release smoke | pending | ``docs/evidence-followups.md`` |

## Item 2: Claude OAuth Import On macOS

- [ ] Claude Code fully quit before OAuth commands.
- [ ] `any-switch doctor claude` showed no Claude process rows, or only a documented process-probe warning unrelated to a running Claude app.
- [ ] `any-switch import-current claude manual-macos --kind oauth_capture` succeeded.
- [ ] `any-switch show claude-manual-macos` showed `oauth_capture` and required identity fields.
- [ ] `any-switch status claude` reported `matched`.

Evidence:

```text
paste redacted command output here
```

## Deferred Full-Coverage Experiments

The following sections are not current-stage release blockers. Complete them
before claiming full ``docs/design.md`` section 13 coverage, or keep their
follow-up tracking current in ``docs/evidence-followups.md``.

## Preflight A: Claude Refresh Token Rotation

- [ ] Capture hashes recorded before Claude Code refresh.
- [ ] Claude Code used long enough to trigger refresh, then quit.
- [ ] `any-switch use claude-manual-macos` was confirmed by typing `yes`, then completed or failed with the expected safety error.
- [ ] Capture hash / manifest behavior recorded.

Conclusion:

```text
write observed rotation behavior here
```

## Preflight B: Claude Keychain / oauthAccount Mismatch

- [ ] External backups created before mutation.
- [ ] Only one side was modified.
- [ ] Claude Code startup behavior recorded.
- [ ] External backups restored.
- [ ] `any-switch import-current claude ... --kind oauth_capture` behavior recorded.

Conclusion:

```text
write observed mismatch behavior here
```

## Preflight C: Claude Runtime JSON Sampling

- [ ] Runtime writes to `~/.claude.json` observed.
- [ ] `oauthAccount` write grouping recorded, and whether top-level `userID` changes independently was noted.
- [ ] JSON formatting, newline behavior, and key order recorded.

Conclusion:

```text
write sampled JSON behavior here
```

## Item 3: Claude OAuth Import On Linux

- [ ] Claude Code fully stopped.
- [ ] `any-switch import-current claude manual-linux --kind oauth_capture` succeeded.
- [ ] `any-switch show claude-manual-linux` showed `oauth_capture` and required identity fields.
- [ ] `any-switch status claude` reported `matched`.
- [ ] `captures/claude-manual-linux/credentials.json` and `manifest.json` existed.

Evidence:

```text
paste redacted command output here
```

## Item 5: Restart Smoke Tests

Run on macOS, Linux, and Windows for each supported app/profile kind available
on that platform.

| OS | App | Profile A | Profile B | A visible after restart | B visible after restart | Pass |
|----|-----|-----------|-----------|--------------------------|--------------------------|------|
|    |     |           |           |                          |                          |      |

Evidence:

```text
paste redacted command output and app-visible observations here
```

## Windows Release Smoke Test

- [ ] Windows archive checksum verified.
- [ ] Archive extracted and contained `any-switch.exe`.
- [ ] `any-switch.exe --version` succeeded.
- [ ] `any-switch.exe apps` succeeded.
- [ ] `any-switch.exe doctor` succeeded without packaging/startup failure.

Evidence:

```text
paste redacted command output here
```

## Preflight E: Codex External Restore Flow

- [ ] Initial Codex profile imported.
- [ ] Codex auth changed outside any-switch.
- [ ] Intended state restored outside any-switch.
- [ ] `any-switch import-current codex manual-codex-refresh --kind auto` succeeded.
- [ ] `any-switch status codex` reported the expected state.

Conclusion:

```text
write observed import/refresh behavior here
```

## Final Decision

- [ ] Every current-stage release blocker is marked `passed`.
- [ ] Deferred Linux / Windows evidence has linked follow-up tracking.
- [ ] Any `failed` or `skipped` item has a linked follow-up issue.
- [ ] Release notes describe this as a macOS-evidenced stage release and do not claim full `docs/design.md` section 13 coverage until deferred evidence is complete.

Decision notes:

```text
write final release decision here
```

Detailed steps and passing criteria are in `docs/manual-verification.md`.
'@
    Add-Content -LiteralPath $Output -Value $manualSections
} finally {
    if (-not [string]::IsNullOrWhiteSpace($temporarySwitchHome) -and (Test-Path -LiteralPath $temporarySwitchHome)) {
        Remove-Item -LiteralPath $temporarySwitchHome -Recurse -Force
    }
}

Write-Output "wrote $Output"
