#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: manual-evidence.sh [output.md]" >&2
  echo "set ANY_SWITCH_BIN=/path/to/any-switch to test a packaged binary" >&2
  echo "set ANY_SWITCH_HOME=/abs/path-under-home to use an existing any-switch home" >&2
  echo "without ANY_SWITCH_HOME, a temporary any-switch home is created and removed" >&2
  echo "refuses to overwrite an existing evidence file" >&2
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

any_switch="${ANY_SWITCH_BIN:-any-switch}"
timestamp="$(date -u '+%Y%m%dT%H%M%SZ')"
output="${1:-manual-evidence-${timestamp}.md}"

if [[ -e "${output}" ]]; then
  echo "evidence file already exists: ${output}" >&2
  echo "choose a new output path or remove the existing file first" >&2
  exit 2
fi

if ! command -v "${any_switch}" >/dev/null 2>&1 && [[ ! -x "${any_switch}" ]]; then
  echo "any-switch binary not found: ${any_switch}" >&2
  usage
  exit 2
fi

umask 077

temporary_switch_home=""
switch_home_note="provided by environment"
if [[ -z "${ANY_SWITCH_HOME:-}" ]]; then
  temporary_switch_home="${HOME:?}/.any-switch-manual-evidence-${timestamp}-$$"
  mkdir -p "${temporary_switch_home}"
  export ANY_SWITCH_HOME="${temporary_switch_home}"
  switch_home_note="temporary; removed when this script exits"
fi

cleanup() {
  if [[ -n "${temporary_switch_home}" && -d "${temporary_switch_home}" ]]; then
    rm -rf "${temporary_switch_home}"
  fi
}
trap cleanup EXIT

run_section() {
  local title="$1"
  shift
  local tmp
  tmp="$(mktemp)"
  {
    printf '\n## %s\n\n' "${title}"
    printf '```text\n'
    printf '$'
    printf ' %q' "$@"
    printf '\n'
  } >>"${output}"
  if "$@" >"${tmp}" 2>&1; then
    redact_output "${tmp}" >>"${output}"
  else
    local status=$?
    redact_output "${tmp}" >>"${output}"
    printf '\n[exit status: %s]\n' "${status}" >>"${output}"
  fi
  printf '```\n' >>"${output}"
  rm -f "${tmp}"
}

redact_output() {
  sed -E \
    -e 's/[[:alnum:]_.%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}/<email>/g' \
    -e 's/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/<uuid>/g' \
    -e 's/"(name|displayName|organization_name|organizationName)"[[:space:]]*:[[:space:]]*"([^"\\]|\\.)*"/"\1":"<identity>"/g' \
    -e 's/(^|[[:space:]])account=[^[:space:]]+/\1account=<identity>/g' \
    "$1"
}

{
  printf '# Manual Verification Evidence\n\n'
  printf 'Generated by `scripts/manual-evidence.sh` on `%s`.\n\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf 'This file is a starting point for `docs/manual-verification.md`. Email addresses, UUID-like identifiers, common JSON identity names, and keychain account labels are redacted automatically; review it before sharing and redact any additional local paths or identities your release process treats as private.\n\n'
  printf '## Environment\n\n'
  printf -- '- Date: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf -- '- Operator:\n'
  printf -- '- OS and version:\n'
  printf -- '- CPU architecture: %s\n' "$(uname -m)"
  printf -- '- `any-switch --version`:\n'
  printf -- '- Git commit:\n'
  printf -- '- Claude Code version:\n'
  printf -- '- Codex CLI version:\n'
  printf -- '- `ANY_SWITCH_HOME` used: %s\n' "${ANY_SWITCH_HOME:-<default>}"
  printf -- '- `ANY_SWITCH_HOME` note: %s\n' "${switch_home_note}"
} >"${output}"

run_section "Host OS" uname -a
if command -v sw_vers >/dev/null 2>&1; then
  run_section "macOS Version" sw_vers
elif [[ -r /etc/os-release ]]; then
  run_section "Linux Version" sh -c 'cat /etc/os-release'
fi
run_section "any-switch Version" "${any_switch}" --version
run_section "any-switch Apps" "${any_switch}" apps
if command -v git >/dev/null 2>&1 && git rev-parse --show-toplevel >/dev/null 2>&1; then
  run_section "Git Commit" git rev-parse HEAD
fi
if command -v claude >/dev/null 2>&1; then
  run_section "Claude Code Version" claude --version
else
  {
    printf '\n## Claude Code Version\n\n'
    printf '```text\nclaude not found in PATH\n```\n'
  } >>"${output}"
fi
if command -v codex >/dev/null 2>&1; then
  run_section "Codex CLI Version" codex --version
else
  {
    printf '\n## Codex CLI Version\n\n'
    printf '```text\ncodex not found in PATH\n```\n'
  } >>"${output}"
fi

run_section "any-switch Doctor" "${any_switch}" doctor
run_section "Claude Doctor" "${any_switch}" doctor claude
run_section "Claude Status JSON" "${any_switch}" status claude --json
run_section "Codex Doctor" "${any_switch}" doctor codex
run_section "Codex Status JSON" "${any_switch}" status codex --json

{
  cat <<'EOF'

## Local Gate

- [ ] `scripts/verify-local.sh` passed.

Evidence:

```text
paste command summary here
```

## Evidence Summary

Use `pending`, `passed`, `failed`, or `skipped: <linked issue>` as the status.
For the current release stage, the macOS Claude OAuth import evidence is
release-blocking. Broader restart, risk-experiment, Linux, and Windows evidence
is deferred and must have follow-up tracking before this stage is released. Use
`docs/evidence-followups.md` for in-repository tracking until a repository issue
or release checklist exists. Do not claim full section 13 coverage while any
deferred item is still pending, failed, or skipped.

### Current-Stage Release Blockers

| Item | Status | Evidence location or follow-up issue |
|------|--------|---------------------------------------|
| 2: macOS Claude OAuth import | pending | |

### Deferred Follow-Up Evidence

| Item | Status | Evidence location or follow-up issue |
|------|--------|---------------------------------------|
| 5-macOS: restart smoke tests | pending | `docs/evidence-followups.md` |
| A-macOS: Claude refresh-token rotation | pending | `docs/evidence-followups.md` |
| B-macOS: Claude source mismatch behavior | pending | `docs/evidence-followups.md` |
| C-macOS: Claude runtime JSON sampling | pending | `docs/evidence-followups.md` |
| E-macOS: Codex external restore flow | pending | `docs/evidence-followups.md` |
| 3: Linux Claude OAuth import | pending | `docs/evidence-followups.md` |
| 5-Linux: restart smoke tests | pending | `docs/evidence-followups.md` |
| 5-Windows: restart smoke tests | pending | `docs/evidence-followups.md` |
| W: Windows release smoke | pending | `docs/evidence-followups.md` |

## Item 2: Claude OAuth Import On macOS

- [ ] Claude Code fully quit before OAuth commands.
- [ ] `any-switch doctor claude` showed no Claude process rows, or only a documented process-probe warning unrelated to a running Claude app.
- [ ] `any-switch import-current claude manual-macos --kind oauth_capture` succeeded.
- [ ] `any-switch show claude-manual-macos` showed `oauth_capture` and required identity fields.
- [ ] `any-switch status claude` reported `matched`.

Evidence:

```text
paste redacted command output here
```

## Deferred Full-Coverage Experiments

The following sections are not current-stage release blockers. Complete them
before claiming full \`docs/design.md\` section 13 coverage, or keep their
follow-up tracking current in \`docs/evidence-followups.md\`.

## Preflight A: Claude Refresh Token Rotation

- [ ] Capture hashes recorded before Claude Code refresh.
- [ ] Claude Code used long enough to trigger refresh, then quit.
- [ ] `any-switch use claude-manual-macos` was confirmed by typing `yes`, then completed or failed with the expected safety error.
- [ ] Capture hash / manifest behavior recorded.

Conclusion:

```text
write observed rotation behavior here
```

## Preflight B: Claude Keychain / oauthAccount Mismatch

- [ ] External backups created before mutation.
- [ ] Only one side was modified.
- [ ] Claude Code startup behavior recorded.
- [ ] External backups restored.
- [ ] `any-switch import-current claude ... --kind oauth_capture` behavior recorded.

Conclusion:

```text
write observed mismatch behavior here
```

## Preflight C: Claude Runtime JSON Sampling

- [ ] Runtime writes to `~/.claude.json` observed.
- [ ] `oauthAccount` write grouping recorded, and whether top-level `userID` changes independently was noted.
- [ ] JSON formatting, newline behavior, and key order recorded.

Conclusion:

```text
write sampled JSON behavior here
```

## Item 3: Claude OAuth Import On Linux

- [ ] Claude Code fully stopped.
- [ ] `any-switch import-current claude manual-linux --kind oauth_capture` succeeded.
- [ ] `any-switch show claude-manual-linux` showed `oauth_capture` and required identity fields.
- [ ] `any-switch status claude` reported `matched`.
- [ ] `captures/claude-manual-linux/credentials.json` and `manifest.json` existed.

Evidence:

```text
paste redacted command output here
```

## Item 5: Restart Smoke Tests

Run on macOS, Linux, and Windows for each supported app/profile kind available
on that platform.

| OS | App | Profile A | Profile B | A visible after restart | B visible after restart | Pass |
|----|-----|-----------|-----------|--------------------------|--------------------------|------|
|    |     |           |           |                          |                          |      |

Evidence:

```text
paste redacted command output and app-visible observations here
```

## Windows Release Smoke Test

- [ ] Windows archive checksum verified.
- [ ] Archive extracted and contained `any-switch.exe`.
- [ ] `any-switch.exe --version` succeeded.
- [ ] `any-switch.exe apps` succeeded.
- [ ] `any-switch.exe doctor` succeeded without packaging/startup failure.

Evidence:

```text
paste redacted command output here
```

## Preflight E: Codex External Restore Flow

- [ ] Initial Codex profile imported.
- [ ] Codex auth changed outside any-switch.
- [ ] Intended state restored outside any-switch.
- [ ] `any-switch import-current codex manual-codex-refresh --kind auto` succeeded.
- [ ] `any-switch status codex` reported the expected state.

Conclusion:

```text
write observed import/refresh behavior here
```

## Final Decision

- [ ] Every current-stage release blocker is marked `passed`.
- [ ] Deferred Linux / Windows evidence has linked follow-up tracking.
- [ ] Any `failed` or `skipped` item has a linked follow-up issue.
- [ ] Release notes describe this as a macOS-evidenced stage release and do not claim full `docs/design.md` section 13 coverage until deferred evidence is complete.

Decision notes:

```text
write final release decision here
```

Detailed steps and passing criteria are in `docs/manual-verification.md`.
EOF
} >>"${output}"

echo "wrote ${output}"
